add host runner config

diff --git a/.github/workflows/client-app.yml b/.github/workflows/client-app.yml
--- a/.github/workflows/client-app.yml
+++ b/.github/workflows/client-app.yml
@@ -3,7 +3,7 @@ on:
     paths:
       - client/**
 jobs:
-  test:
+  build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout
@@ -36,3 +36,26 @@ jobs:
           docker build --file .docker/client-app.Dockerfile -t client-app .
           docker tag client-app:latest ${{ secrets.ECR_URL }}:latest
           docker push ${{ secrets.ECR_URL }}:latest
+
+##
+  deploy:
+    needs: build
+    runs-on: client-host-runner
+    steps:
+      - name: Install unzip if not present
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y unzip
+
+      - name: Check and install AWS CLI
+        run: |
+          cd ~
+          if ! command -v aws &> /dev/null
+          then
+              echo "AWS CLI not found. Installing..."
+              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+              unzip awscliv2.zip
+              sudo ./aws/install
+          else
+              echo "AWS CLI is already installed."
+          fi
